/* Research Studio — MVP local-first. No authentication or server persistence. */
(()=>{'use strict';
const STORAGE='research-studio-v1';
const DEFAULT={projects:[],references:[]};
const templates={IMRyD:['Introducción','Métodos','Resultados','Discusión','Conclusiones'],IMRyDI:['Introducción','Métodos','Resultados','Discusión','Implicaciones','Conclusiones'],IDyC:['Introducción','Desarrollo','Conclusiones']};
const guidance={'Introducción':'Delimita el problema, sintetiza evidencia verificable, identifica la brecha, define objetivos y contribución.','Métodos':'Explica diseño, periodo, muestra, selección, instrumentos, variables, ética, procedimiento y análisis de manera reproducible.','Resultados':'Reporta estimaciones, intervalos y tablas sin atribuir causalidad cuando el diseño no lo permite.','Discusión':'Interpreta hallazgos frente a evidencia previa; distingue hipótesis, explicaciones alternativas y limitaciones.','Implicaciones':'Delimita aplicaciones prácticas o teóricas según la evidencia disponible.','Conclusiones':'Responde a los objetivos sin presentar resultados nuevos ni exceder el alcance del estudio.','Desarrollo':'Organiza el argumento teórico, compara perspectivas y documenta cada afirmación sustancial.'};
const uid=()=>globalThis.crypto&&crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random().toString(36).slice(2);
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE));return x&&Array.isArray(x.projects)&&Array.isArray(x.references)?x:structuredClone(DEFAULT)}catch{return structuredClone(DEFAULT)}}
let db=load(),view='dashboard',selected=null,section=null,query='',flash='';
const root=document.querySelector('#app');
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(db));return true}catch{alert('No se pudo guardar. Exporta una copia JSON y revisa el almacenamiento disponible.');return false}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function project(){return db.projects.find(p=>p.id===selected)}
function pct(p){let v=templates[p.model]||[];return Math.round(v.filter(s=>(p.sections[s]||'').trim().length>0).length/Math.max(1,v.length)*100)}
function nav(id,label){return '<button class="'+(view===id?'active':'')+'" data-view="'+id+'">'+label+'</button>'}
function toast(s){flash=s;render();setTimeout(()=>{const e=document.querySelector('#flash');if(e)e.remove()},4000)}
function button(text,action,cls=''){return '<button class="btn '+cls+'" data-action="'+action+'">'+text+'</button>'}
function shell(body){root.innerHTML='<div class="layout"><aside class="side"><div><div class="brand">◈ Research Studio</div><div class="subbrand">ACADEMIC WORKSPACE</div></div><nav class="nav">'+nav('dashboard','▦ &nbsp; Panel general')+nav('projects','▤ &nbsp; Mis artículos')+nav('references','▧ &nbsp; Biblioteca')+nav('settings','⚙ &nbsp; Datos y respaldo')+'<a href="ai.html" style="display:block;color:#fff;background:#345d91;padding:12px 14px;border-radius:11px;text-decoration:none;font-weight:700">✦ &nbsp; Research AI Copilot →</a></nav><div class="sidefooter">Prototipo local • Sin cuentas<br>Los datos permanecen en este navegador.</div></aside><main class="main">'+(flash?'<div id="flash" class="notice success">'+esc(flash)+'</div>':'')+'<div class="notice">Versión de demostración: la información se guarda solo en este navegador. No ingreses manuscritos confidenciales ni datos personales sensibles. La plataforma multiusuario se incorporará con autenticación y controles de acceso.</div>'+body+'</main></div>'}
function header(k,t,desc,action=''){return '<header class="top"><div><div class="eyebrow">'+k+'</div><h1 class="h1">'+t+'</h1><div class="muted">'+desc+'</div></div>'+action+'</header>'}
function projectCard(p){return '<article class="card project"><div class="row"><span class="pill">'+esc(p.model)+'</span><span class="muted small">'+esc(p.status)+'</span></div><h3>'+esc(p.title)+'</h3><div class="muted small">'+esc(p.field||'Área no especificada')+' · '+esc(p.language||'Español')+'</div><div class="progress"><div style="width:'+pct(p)+'%"></div></div><div class="row"><span class="small muted">'+pct(p)+'% de secciones iniciadas</span>'+button('Abrir','open:'+p.id)+'</div></article>'}
function listProjects(arr){return arr.length?'<div class="grid">'+arr.map(projectCard).join('')+'</div>':'<div class="card empty">Todavía no hay artículos. Crea uno para empezar a trabajar.</div>'}
function dashboard(){const total=db.projects.length;return header('Vista general','Tu espacio de investigación','Organiza tus manuscritos y avances desde un solo lugar.',button('+ Nuevo artículo','new'))+'<div class="stats"><div class="card"><div class="muted small">Artículos</div><div class="statnum">'+total+'</div></div><div class="card"><div class="muted small">En progreso</div><div class="statnum">'+db.projects.filter(p=>pct(p)>0&&pct(p)<100).length+'</div></div><div class="card"><div class="muted small">Referencias</div><div class="statnum">'+db.references.length+'</div></div></div><h2>Artículos recientes</h2>'+listProjects([...db.projects].reverse().slice(0,6))}
function projects(){return header('Manuscritos','Mis artículos','Cada proyecto conserva sus secciones y metadatos.',button('+ Crear artículo','new'))+listProjects(db.projects.filter(p=>p.title.toLowerCase().includes(query.toLowerCase())))}
function form(){return header('Proyecto','Nuevo artículo','Puedes modificar estos datos posteriormente.')+'<div class="card" style="max-width:730px"><form id="newProject"><div class="field"><label>Título provisional *</label><input name="title" required maxlength="250" placeholder="Título de la investigación"></div><div class="field"><label>Área temática</label><input name="field" maxlength="120" placeholder="Administración, marketing, educación..."></div><div class="field"><label>Estructura</label><select name="model"><option>IMRyD</option><option>IMRyDI</option><option>IDyC</option></select></div><div class="field"><label>Idioma</label><select name="language"><option>Español</option><option>English</option></select></div><div class="field"><label>Revista objetivo (opcional)</label><input name="journal" maxlength="180"></div><div class="toolbar"><button class="btn" type="submit">Crear y abrir editor</button>'+button('Cancelar','cancel','secondary')+'</div></form></div>'}
function editor(){const p=project();if(!p){view='projects';return projects()}const secs=templates[p.model];if(!secs.includes(section))section=secs[0];return header('Workspace / '+esc(p.model),esc(p.title),'Edita cada sección. Los cambios se guardan automáticamente en el dispositivo.',button('← Proyectos','back','secondary'))+'<div class="editor"><div class="sections">'+secs.map(s=>'<button class="'+(section===s?'active':'')+'" data-section="'+esc(s)+'">'+esc(s)+(p.sections[s]?' ✓':'')+'</button>').join('')+'</div><div class="card"><div class="row"><h2>'+esc(section)+'</h2><span class="pill">'+pct(p)+'% iniciado</span></div><p class="hint">'+esc(guidance[section]||'')+'</p><div class="field"><label>Contenido de la sección</label><textarea id="sectionContent" placeholder="Escribe aquí el contenido académico...">'+esc(p.sections[section]||'')+'</textarea></div><div class="row"><span class="muted small" id="savedState">Guardado local activo</span><span class="small muted" id="wordCount">0 palabras</span></div><div class="toolbar">'+button('Descargar manuscrito (.txt)','txt')+button('Exportar respaldo (.json)','backup','secondary')+button('Eliminar proyecto','remove','danger')+'</div><hr style="border:0;border-top:1px solid #e1e7f0;margin:24px 0"><h3>Ficha de investigación</h3><div class="field"><label>Objetivo de investigación</label><textarea id="objective" style="min-height:80px">'+esc(p.objective||'')+'</textarea></div><div class="field"><label>Notas / preguntas pendientes</label><textarea id="notes" style="min-height:80px">'+esc(p.notes||'')+'</textarea></div><p class="muted small">La exportación DOCX, las citas insertables y las revisiones con IA se añadirán en una siguiente fase.</p></div></div>'}
function refs(){return header('Fuentes','Biblioteca bibliográfica','Registra referencias reales con DOI o URL. Esta versión no verifica automáticamente metadatos.',button('+ Nueva referencia','addref'))+'<div class="references">'+(db.references.length?db.references.map(r=>'<div class="refitem"><div class="row"><strong>'+esc(r.title)+'</strong>'+button('Eliminar','delref:'+r.id,'danger')+'</div><p>'+esc(r.authors||'Autor sin registrar')+' · '+esc(r.year||'Año pendiente')+'</p><p>'+esc(r.doi||r.url||'Sin identificador')+'</p></div>').join(''):'<div class="card empty">Todavía no hay referencias registradas.</div>')+'</div>'}
function refForm(){return header('Biblioteca','Nueva referencia','Registra solo fuentes cuya información hayas contrastado.')+'<div class="card" style="max-width:730px"><form id="newRef"><div class="field"><label>Título *</label><input name="title" required maxlength="350"></div><div class="field"><label>Autores</label><input name="authors" maxlength="300"></div><div class="field"><label>Año</label><input name="year" inputmode="numeric" maxlength="4" pattern="[0-9]{4}"></div><div class="field"><label>DOI</label><input name="doi" maxlength="250"></div><div class="field"><label>URL</label><input name="url" type="url" maxlength="500"></div><div class="toolbar"><button class="btn" type="submit">Guardar referencia</button>'+button('Cancelar','refs','secondary')+'</div></form></div>'}
function settings(){return header('Datos','Respaldo y privacidad','Protege los avances realizando copias periódicas.')+'<div class="card"><h2>Exportar respaldo</h2><p class="muted">Descarga todos los proyectos y referencias en formato JSON. Podrás restaurarlos en este navegador o en otro dispositivo.</p>'+button('Descargar respaldo JSON','backup')+'<hr style="border:0;border-top:1px solid #e1e7f0;margin:24px 0"><h2>Importar respaldo</h2><div class="field"><label>Seleccionar archivo JSON de Research Studio</label><input id="restoreFile" type="file" accept=".json,application/json"></div><p class="small muted">La importación reemplazará todos los datos actuales tras confirmación.</p><hr style="border:0;border-top:1px solid #e1e7f0;margin:24px 0"><h2>Privacidad</h2><p class="muted">Esta versión no sincroniza ni comparte datos entre usuarios. La eliminación de datos del navegador podría borrar los proyectos si no conservas una copia.</p></div>'}
function render(){shell(({dashboard,projects,new:form,editor,references:refs,addref:refForm,settings})[view]?.()||dashboard());if(view==='editor'){const e=document.querySelector('#sectionContent');if(e){const count=()=>document.querySelector('#wordCount').textContent=(e.value.trim()?e.value.trim().split(/\s+/).length:0)+' palabras';e.addEventListener('input',()=>{const p=project();p.sections[section]=e.value;p.updatedAt=new Date().toISOString();const ok=save();document.querySelector('#savedState').textContent=ok?'Guardado en este navegador':'Error al guardar';count()});count()}for(const field of ['objective','notes']){document.querySelector('#'+field)?.addEventListener('input',e=>{project()[field]=e.target.value;save()})}}}
function download(name,content,type){const b=new Blob([content],{type});const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportJSON(){download('research-studio-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({format:'research-studio-v1',exportedAt:new Date().toISOString(),data:db},null,2),'application/json')}
function exportTXT(){const p=project(),content=p.title+'\n'+(p.journal?'Revista objetivo: '+p.journal+'\n':'')+'\n'+templates[p.model].map(s=>s.toUpperCase()+'\n\n'+(p.sections[s]||'')+'\n').join('\n');download((p.title.replace(/[^a-z0-9áéíóúüñ -]/gi,'').slice(0,48).trim()||'manuscrito')+'.txt',content,'text/plain;charset=utf-8')}
root.addEventListener('click',e=>{const n=e.target.closest('[data-view],[data-action],[data-section]');if(!n)return;if(n.dataset.view){view=n.dataset.view;query='';render();return}if(n.dataset.section){section=n.dataset.section;render();return}const act=n.dataset.action||'';if(act==='new')view='new';else if(act==='cancel'||act==='back')view='projects';else if(act==='refs')view='references';else if(act==='addref')view='addref';else if(act==='backup'){exportJSON();return}else if(act==='txt'){exportTXT();return}else if(act.startsWith('open:')){selected=act.slice(5);view='editor';section=null}else if(act==='remove'){if(!confirm('¿Eliminar este artículo y todas sus secciones? Esta acción no se puede deshacer.'))return;db.projects=db.projects.filter(p=>p.id!==selected);save();selected=null;view='projects'}else if(act.startsWith('delref:')){if(!confirm('¿Eliminar esta referencia?'))return;db.references=db.references.filter(r=>r.id!==act.slice(7));save()}else return;render()});
root.addEventListener('submit',e=>{if(e.target.id==='newProject'){e.preventDefault();const f=new FormData(e.target),p={id:uid(),title:String(f.get('title')).trim(),field:String(f.get('field')).trim(),model:String(f.get('model')),language:String(f.get('language')),journal:String(f.get('journal')).trim(),status:'Borrador',sections:{},objective:'',notes:'',createdAt:new Date().toISOString()};if(!p.title)return;db.projects.push(p);save();selected=p.id;section=null;view='editor';render()}else if(e.target.id==='newRef'){e.preventDefault();const f=new FormData(e.target);db.references.push({id:uid(),title:String(f.get('title')).trim(),authors:String(f.get('authors')).trim(),year:String(f.get('year')).trim(),doi:String(f.get('doi')).trim(),url:String(f.get('url')).trim()});save();view='references';render()}});
root.addEventListener('change',async e=>{if(e.target.id!=='restoreFile')return;const f=e.target.files?.[0];if(!f)return;try{if(f.size>8e6)throw Error('El archivo supera el máximo admitido de 8 MB.');const raw=JSON.parse(await f.text());if(raw.format!=='research-studio-v1'||!raw.data||!Array.isArray(raw.data.projects)||!Array.isArray(raw.data.references))throw Error('El archivo no tiene el formato de respaldo esperado.');if(!confirm('Esto reemplazará TODOS los proyectos y referencias actuales. ¿Continuar?'))return;db=raw.data;save();view='dashboard';selected=null;toast('Respaldo importado correctamente.')}catch(err){alert('No se pudo importar: '+err.message)}});
render();
})();